### ISSUE TITLE
AbstractFilter set as shader doesn't receive texture changes in v3

### ISSUE THREAD

**Issue by oal** [GoodBoyDigital/pixi.js#1471] opened 2015-02-27 17:22 UTC
Thanks for the quick replies yesterday. I've done some more testing of the new version, and it seems like when I set my filter (extended from AbstractFilter, only adding a few extra uniforms, and changing the fragment shader) as a shader (.shader property of a sprite), changes to the sprite's texture doesn't get picked up. However if I set it as a .filter, then it works as expected.

I do call `.update()` on the texture, and the fact that it works as a .filter, makes me think this is a bug.

**Comment by GoodBoyDigital** [comment] 2015-02-27 17:27
thanks for the heads up! do you have some code that we could debug? Makes it way easier :D cheers!

**Comment by oal** [comment] 2015-02-27 17:37
Here: http://static.olav.it/b2d/

It's weird, because when I uploaded it to my server, it seems to work, but on localhost, it doesn't. It works in both cases when used on the .filter property, though. It could be a problem on my end, but I'm not sure how that's explain the fact that it works as `.filter`.

**Comment by oal** [comment] 2015-02-27 18:08
Ok, the reason it worked when uploaded to my server, and not on localhost was that the texture path was wrong after I uploaded it. After fixing that, I get the same behavior in both places. If I simply don't send my texture as a uniform, it works (just as it did when it didn't find the textures.png).

So I have two textures: The sprite's own texture (created from a canvas), and the textures.png from which I'm sampling to get dirt/gold/stone textures instead of plain colors. The sampling of those doesn't work yet, though, which is why I didn't notice the textures file couldn't be found.

**Comment by oal** [comment] 2015-02-27 18:17
Sorry about spamming your inboxes, but digging further, it seems that it uses the same sprite texture for all the sprites using the same shader (so if 10 sprites use the same shader instance, sampling uSampler in the shader always samples one of them). This may actually be the way it's intended, but if so, should be explained in the docs somehow. So: Many sprites can use the same filter instance, and it'll sample the sprite's own texture, but when many sprites use the same shader, they will all sample (uSampler), from one of them (the last one added, it seems).

**Comment by oal** [comment] 2015-02-27 18:28
Nope, this is definitely a bug. When passing in a `sampler2D`/image as a uniform (under any name) to a shader, uSampler no longer samples from the sprite's own texture. Removing the additional `sampler2D` uniform, it works again.

I've updated the code above ^ and you can see the texture "flickers" immediately after the page loads, and then displays the texture of the last added sprite (so uSampler for all sprites is the same).

I also make sure that a new instance of my AbstractFilter child class is made for each sprite, as opposed to before, when I used the same instance for all. That does not seem to have helped, though.

**Comment by GoodBoyDigital** [comment] 2015-02-28 10:42
Good catch @oal ! going to look into this over the wknd!

**Comment by englercj** [comment] 2015-02-28 16:20
Duplicate of #1427, thanks for the info, lets track it there.

**Closed by englercj** 2015-02-28 16:20 UTC
