### ISSUE TITLE
TilingSprite incorrect scaling in 3.02

### ISSUE THREAD

**Issue by weepy** [GoodBoyDigital/pixi.js#1751] opened 2015-05-05 09:13 UTC
Heya, I noticed that the tiling sprite doesn't seem to quite correctly rendered. It appears to repeat 1px too early.

Here's a test : https://jsfiddle.net/ya9b73qk/

I noticed that if you set tiles.scale to be (1+size)/size it's more correct, but of course you get some pretty bad aliasing then ... 

J

**Comment by englercj** [comment] 2015-05-05 14:00
Duplicate of #1683?

**Comment by weepy** [comment] 2015-05-05 16:03
I suspect its similar underlying but has different symptoms.

**Comment by englercj** [comment] 2015-05-08 22:43
Closing, fixed this with #1683!

**Closed by englercj** 2015-05-08 22:43 UTC
Labels: bug
