### ISSUE TITLE
Masks are Y flipped if `cacheAsBitmap` is enabled in a DisplayObjectContainer with WebGL renderer

### ISSUE THREAD

**Issue by lodr** [GoodBoyDigital/pixi.js#1358] opened 2015-01-17 20:18 UTC
This fiddle shows how masks are flipped in Y-axis when `cacheAsBitmap` is set to true:
http://jsfiddle.net/Lk66gt1t/4/

This does not happen with Canvas render.

**Comment by englercj** [comment] 2015-01-17 22:05
Duplicate of #1293

**Closed by englercj** 2015-01-17 22:05 UTC

**Comment by lodr** [comment] 2015-01-19 09:42
I though as the my example involves masks, it could be a little bit different. Just noticing that detail.
