### ISSUE TITLE
generateTexture on Firefox renders unexpected black background

### ISSUE THREAD

**Issue by jwdunn1** [GoodBoyDigital/pixi.js#1858] opened 2015-06-02 15:08 UTC
Repro: http://jsfiddle.net/intrinsica/v0xwyu2w/

I've reduced the case to drawing only one shape, adding to the masterImage container, and then generating a texture from which a stamp is created for use in making a sprite to add to the stage. On Firefox (I'm using version 38.0.5), a black background is rendered. Expected is a white background as rendered in Chrome, Safari, Opera, IE, Maxthon. Is this a browser issue?

![ff](https://cloud.githubusercontent.com/assets/4262131/7938726/e73c4ee8-08fb-11e5-9338-a8f644fb618e.PNG)

**Comment by UncleAcid** [comment] 2015-06-03 15:41
I'm also running Firefox 38.0.5 (OSX) and it works fine for me.

**Comment by englercj** [comment] 2015-06-03 17:47
Duplicate of #1636 I believe.

**Closed by englercj** 2015-06-03 17:47 UTC
