### ISSUE TITLE
bugged coordinates after many drawing instructions

### ISSUE THREAD

**Issue by luk-bertrand** [GoodBoyDigital/pixi.js#1423] opened 2015-02-09 19:18 UTC
Hi !
I'm a beginer of this awesome framework ! I started by make a paint application.
I'm faced a strange behavior.
Difficult to explain, draw about a hundred tiles here : http://jsfiddle.net/83w5m3xd/
Here is the layers tree :
stage
-- |- Board (PIXI.DisplayObjectContainer)
 -------  |- canvas (PIXI.Graphics) 
 -------  |- grid (PIXI.Graphics)
After drawing many instructions <beginFill>instruction</endFill> (often 13116) in the canvas object, the painter bug but datas are still correct after.
In canvas renderer, the bug doesn't exist, the speed is just much slower because of length of graphicsData i suppose.
In the demo, Pixi draw 13000 instructions at the begining.
On the screen, the drag bugged shape come back in linear way to the first canvas instructions (coordinates and color).
Thanks for all !

**Comment by englercj** [comment] 2015-02-10 00:27
Perhaps a duplicate of #1076?

**Comment by luk-bertrand** [comment] 2015-02-10 13:38
I very suspect a similitude ! This behavior to want to come back at the origin and the linear color effect is the same.

**Comment by englercj** [comment] 2015-02-10 15:02
Going to track this in #1076.

**Closed by englercj** 2015-02-10 15:02 UTC
Labels: duplicate
