### ISSUE TITLE
Drawing gets all messed up like it is hitting some sort of limit?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [GoodBoyDigital/pixi.js#1396] opened 2015-01-30 06:50 UTC
Hiya, encountering some sort of drawing glitch on my code pen, Only present in WebGLRenderer does not happen in CanvasRenderer.

To reproduce, Click Stress Test button 9-10 times
Test Case: http://codepen.io/LiamKarlMitchell/pen/MYvPNv
Original Code: http://codepen.io/LiamKarlMitchell/pen/zImip

What it should look like,
![image](https://cloud.githubusercontent.com/assets/1968109/5972088/567666a8-a8b8-11e4-99a1-4bf616fb5f1b.png)

![image](https://cloud.githubusercontent.com/assets/1968109/5971837/68c4aafe-a8b3-11e4-8d83-7209fbd0730f.png)

What happens after to many circles are drawn.
![image](https://cloud.githubusercontent.com/assets/1968109/5972084/4a2e64f4-a8b8-11e4-817f-450d4895a1be.png)

![image](https://cloud.githubusercontent.com/assets/1968109/5971831/47018ab8-a8b3-11e4-8a31-292947080462.png)

Is this some kind of limitation or am I coding the drawing of many objects at once wrong?
Is there a better way to render so many things at once? Should I use sprite rather than line drawing?

I am using Windows 7 64bit, Google Chrome Version Version 39.0.2171.65 m and Google Chrome Version 41.0.2225.0 canary (64-bit)

It also had the problem in Firefox, so I don't think it is a browser issue.
I have seen this happen on PixiJS version 2.2.3 and 1.5.1.

Reading comments on https://github.com/GoodBoyDigital/pixi.js/issues/364 It seems like I should not draw this many shapes and should use textures.

If this is the best advice I will just use fromImage and load my images from base64 data uri hidden on the html. (Since I don't have codepen pro) and this issue could possibly be closed.

Thanks for your input.

**Comment by englercj** [comment] 2015-01-30 15:59
Pretty sure this is a duplicate of #1076, thanks for the info!

**Closed by englercj** 2015-01-30 15:59 UTC
