### ISSUE TITLE
[v3 RC4] PIXI.Graphics fails to render on new WebGL context

### ISSUE THREAD

**Issue by saschagehlich** [GoodBoyDigital/pixi.js#1635] opened 2015-04-06 21:36 UTC
Example (see console): http://jsfiddle.net/ju7vmxsf/

* Create a WebGLRenderer with a Graphics object
* Render it -> Graphics object is not dirty anymore
* Destroy WebGLRenderer, create a new one
* Render it -> Graphics object still not dirty -> updateGraphics() not called -> Graphics not known in WebGL context
* :boom:

**Comment by adelciotto** [comment] 2015-04-07 13:55
Checking whether or not the graphics object exists within the new webGL context seems to stop the error:
i.e.
```javascript
GraphicsRenderer.prototype.render = function(graphics)
{
....
     // if the graphics object does not exist in the webGL context time to create it!
    var webGL = graphics._webGL[gl.id];
    if (!webGL)
    {
        webGL = graphics._webGL[gl.id] = {lastIndex:0, data:[], gl:gl};
    }

....
}
```
 theres probably a better solution though.

**Comment by englercj** [comment] 2015-04-11 16:47
Duplicate of #1600.

**Closed by englercj** 2015-04-11 16:47 UTC
Labels: bug, duplicate, WebGL
