### ISSUE TITLE
Build and destroy game on webGL  rendering

### ISSUE THREAD

**Issue by maksmaers** [GoodBoyDigital/pixi.js#1721] opened 2015-04-25 07:54 UTC
I have an issue with game destroy on webGL rendering.

Reproducing:
In the following example of creating animation on PIXI,
just need to build and destroy the game for 5 times
So here is simple example of the issue:
http://jsfiddle.net/07gy4p6e/3/

Before:
![screen shot 2015-04-25 at 10 50 15](https://cloud.githubusercontent.com/assets/1178783/7332138/1133ef34-eb39-11e4-8def-3993e8a2121b.png)
After  fifth iteration of building and destroying :
![screen shot 2015-04-24 at 14 30 49](https://cloud.githubusercontent.com/assets/1178783/7332143/2bb533f4-eb39-11e4-8f54-8c9f42fab379.png)

On the fifth iteration of building and destroying the texture is transformed into back rectangle,
but on Canvas rendering everything works fine for any iteration.

Is someone met with this error in the past? How is it possible to handle this issue?
Thanks

**Comment by englercj** [comment] 2015-04-25 14:42
Looks like you are using v2.2.9, I'm pretty sure this issue does not exist in our latest release v3.0.1.

As for v2, IIRC it is caused by this line:

https://github.com/GoodBoyDigital/pixi.js/blob/v2.x/src/pixi/textures/BaseTexture.js#L110

It is hard-coded to 5, I recommend updating to v3 to solve the issue.

**Comment by pietro909** [comment] 2015-04-25 16:11
Wow! I was about opening the same issue :+1: 
And here @maksmaers fiddle forked and modified for v.3 http://jsfiddle.net/pietro909/he4du5jo/1/

it works, thank you guys!

**Comment by englercj** [comment] 2015-04-25 16:31
Awesome, going to close this now since we definitely fixed this in v3.

Please upgrade!

**Closed by englercj** 2015-04-25 16:31 UTC
