### ISSUE TITLE
Runtime errors with IE 11

### ISSUE THREAD

**Issue by shanemccartney** [GoodBoyDigital/pixi.js#1383] opened 2015-01-27 08:56 UTC
After testing a recent project on IE 11 we get the following errors in the console. Does PIXI support IE 11 with WebGL? When this error occurs it seems to not show any DisplayObjects which require a texture source like that we source from an atlas.

If you would like to know specifically the source code that all these errors happen feel free to ask for more info, if it helps. It seems there are features that PIXI relies on that IE 11 does not support my best guess.

This was tested with v2.2.3

![screen shot 2015-01-27 at 7 42 47 pm](https://cloud.githubusercontent.com/assets/4735713/5915789/1e2c1e34-a65e-11e4-8b54-b0c6ddaacc8a.png)

**Comment by englercj** [comment] 2015-01-27 15:33
We used to use float there, but moved to unsigned byte to fix some rounding issues that were happening. This page seems to suggest that it is supported:

https://msdn.microsoft.com/en-us/library/ie/dn302460(v=vs.85).aspx

> vertexAttribPointer can specify UNSIGNED_BYTE, BYTE, SHORT and UNSIGNED_SHORT for both normalized and un-normalized formats (all component types, 1 through 4, are supported) in Internet Explorer 11 using WebGL renderer version 0.93 and later.

Are you on the latest ie 11?

**Comment by shanemccartney** [comment] 2015-01-27 23:28
I believe its the latest update 11.0.9600.17031 as this was installed with a new Windows 8.1 machine here in the office,

**Comment by shanemccartney** [comment] 2015-01-27 23:30
I think that use of UNSIGNED_BYTE is not supported in ie11 a quick Google search I found this thread https://connect.microsoft.com/IE/feedback/details/814134/ie11-webgl-vertexattribpointer-only-support-the-type-float

**Comment by englercj** [comment] 2015-01-28 00:08
That ticket you linked is closed as "fixed". Seems that version `11.0.9600.17107` is the version with the fix, if I read that correctly it should be released in April.

We can put a fallback in to use FLOAT if in IE 11 but that will cause a regression of all the bugs we fixed by changing it to UNSIGNED_BYTE.

**Comment by shanemccartney** [comment] 2015-01-28 08:08
Yeah I understand what you're saying but this will affect ** I believe ** quite a few projects and developers. I think the best solution really is to not use webgl for ie at all especially if the latest version is not supported . To me I read this as its a bit unstable to use webgl with ie. 

To solve this for our project I will look into how easy it is to set canvas as the renderer we are currently using auto detect for this so not looked into any alternatives as yet.

Let me know if there's a better option?

**Comment by GoodBoyDigital** [comment] 2015-01-28 12:50
Hey man!

IE11 has historically been a bit of a pain with regards to its webGL implementation. The version we tested on when we modified the code worked fine, but I guess it was the most up to date version. 

Until we do get this nailed - The good news is that IE actually has the fastest canvas implementation of all the browsers so performance will not be an issue if you flicked to canvas mode.

**Comment by englercj** [comment] 2015-01-28 14:38
Going to close this for now, since the preferred workaround is to use canvas renderer if on a lower version of IE 11.

**Closed by englercj** 2015-01-28 14:38 UTC
Labels: need-more-info

**Comment by shanemccartney** [comment] 2015-01-28 22:19
ok sure but to clarify the issue here for others as it will affect anyone wanting to support ie 11. The issue is we have installed the very latest ie 11 this is the version I mention. Version asked to be installed is not even out until April this year is that right?  I can also confirm this because by navigating to the ie download site it says we already have the latest. 

So the issue isn't that we are not using the latest its that the latest version of ie 11 doesn't work or hasn't been tested with webgl and pixi. So the only solution then is if ie just use canvas really :(

**Comment by englercj** [comment] 2015-01-28 23:01
11.0.9600.17501 is installed on my Win 7 machine right now, so I'm not sure why you think you have the latest. 11.0.15 (v11.0.9600.17501) was released on 9 December 2014; 50 days ago.

**Comment by shanemccartney** [comment] 2015-01-29 07:54
Yes we've done this and going to the ie website says we have the latest version already but maybe this version as you've got is not supported for the latest operating system Windows 8.1 with 64 bit support.

Enabling only canvas for ie via manually constructing the canvas renderer worked fine as Mat suggested. This was very easy to implement with the heavily utilised if ie javascript check ;) also I agree with Mat the canvas implementation for ie is very performant!!

**Comment by englercj** [comment] 2015-01-29 15:14
On my windows 8.1 x64 machine at home I am running 11.0.9600.17498. After checking for and installing update via Windows Update it updated to 11.0.9600.17501.

**Comment by photonstorm** [comment] 2015-01-29 15:30
Was curious about this so just checked, and on my Win 7 x64 install IE is 11.0.9600.17501 by default. It updated itself automatically via Windows Update, but this is definitely the latest "in the wild" version.

**Comment by shanemccartney** [comment] 2015-01-30 06:43
Anyway this is getting a bit pointless we have installed the very latest windows update today and still we have this version I am not 100% sure why but this is what we are getting.

We cant even manually download the browser because it says I have the latest being ie 11 and I cant update to this version you have because the windows updates are not updating anyway the solution for me is to not bother with webgl on ie as we cant seem to install a version of ie which works with ie and pixi.js. I think you might be willing to accept that maybe this is not working for us.

i wish it was as simple as you say to just update, its not!

**Comment by photonstorm** [comment] 2015-01-30 08:17
I would have thought it would it would be somewhat trivial for Pixi to detect if the current browser supports UNSIGNED_BYTE or not - and if not to force it to use the canvas renderer (as it's blatantly going to screw up if it tries to use WebGL) - should be part of the auto detect. Doesn't even need to be IE specific, as it could manifest anywhere.

**Comment by shanemccartney** [comment] 2015-01-30 10:30
Good suggestion and points too @photostorm would that just be an if null check right? 

I think the issue is many html5 developers are not testing as many device and browser configurations as we are in this build. Personally I think this is a real issue With features that are not supported properly in webgl but are required by pixi. Maybe there's a way to add a handler so if rendering fails for any case then the renderer can be changed to canvas.

As I have been told that  ie makes a majority of windows users and windows is still the most popular os too :)

**Comment by GoodBoyDigital** [comment] 2015-01-30 11:42
great points guys - we will certainly make it part of the autodetect for v3

**Comment by englercj** [comment] 2015-01-30 15:27
> would that just be an if null check right?

I don't think so, `gl.UNSIGNED_BYTE` exists in IE 11 WebGL but is not supported IIRC. That is why I mentioned it would have to be a user-agent string check.
