### ISSUE TITLE
BitmapText bugs with `tint`

### ISSUE THREAD

**Issue by gre** [GoodBoyDigital/pixi.js#1305] opened 2015-01-01 20:29 UTC
I have found 2 bugs in BitmapText when used with tint.

- The first is that if you update `tint` after creating a `BitmapText`, it won't be refresh until you re-set the text, or you explicitly call `.updateText()` (missing a dirty state).

- The second is that it is not possible to use the black tint `0x000000` because of [this code](https://github.com/GoodBoyDigital/pixi.js/blob/master/src/pixi/text/BitmapText.js#L169) which fallbacks to **white** – this behavior is inconsistant to the behavior of a `Sprite`.

**Comment by marcusstenbeck** [comment] 2015-01-04 09:14
@gre Could you make a [jsFiddle](http://jsfiddle.net/) that shows the bug in action?

I'll try to reproduce it on my machine, but to make sure I'm looking at the same problem you're looking at I'd love to get some running code showing the problem.

—Marcus

**Comment by gre** [comment] 2015-01-04 09:48
http://jsfiddle.net/n61590gc/

**Comment by marcusstenbeck** [comment] 2015-01-04 10:26
### Updating tint
Thanks for making the jsFiddle. I noticed that you're setting the `BitmapText.tint`. Right now it looks like Pixi doesn't support setting the attribute directly like you're doing (in fact, tint isn't even metioned in the docs for `BitmapText`). Even so, setting tint directly by assigning a value to the attribute directly makes it impossible for Pixi to know that you've updated (without adding some pretty slow code that keeps track of earlier states). The method [BitmapText.setStyle()](http://www.goodboydigital.com/pixijs/docs/classes/BitmapText.html#method_setStyle) is what you want to be doing. Unfortunately, [BitmapText.setStyle()](http://www.goodboydigital.com/pixijs/docs/classes/BitmapText.html#method_setStyle) won't let you set just one attribute, so you have to copy the previous style on your bitmap text, and change the thing you want to change, and then apply it afterwards. Example below.

```
// Copy the current style
var newStyle = myBitmapText.style;

// Update the tint
newStyle.tint = 0x123456;

// Apply the new style to myBitmapText
myBitmapText.setStyle(newStyle);
```

This is kinda painful, so I'll do a little bit of work to change it so you can specify just one attribute in [BitmapText.setStyle()](http://www.goodboydigital.com/pixijs/docs/classes/BitmapText.html#method_setStyle), changing the needed code to the following.

```
myBitmapText.setStyle({ tint: 0x123456 });
```

What do you think?

### Using black tint
Yeah. That's a bug. I'll get that fixed.

**Comment by gre** [comment] 2015-01-04 11:55
I should have created 2 separated issues, sorry for that.

so about the bug 1, I understand that setting `.tint` is not trigging "dirty", also your solution is ok to me, but my real concern is more about the inconsistencies in PIXI APIs:

Here is the same exact example using Sprite:
http://jsfiddle.net/7c24wonw/1/

I'm not so familiar with the code behind but it looks like that Sprite does watch for tint changes, BitmapText does not. Wouldn't it better to at least have the same behavior? (at best factorize this job?)

**Comment by marcusstenbeck** [comment] 2015-01-04 12:00
I'll have a look. Might not get back to you today through (there's some nice sunny winter weather I need to attend to  ✨).

**Comment by marcusstenbeck** [comment] 2015-01-04 14:49
I had a look at the Sprite class source vs the BitmapText source. It looks like BitmapText uses a bunch of Sprites for the characters. It creates them at instantiation or whenever the `dirty` flag is set.

Sprite actually remembers what the last value of `tint` was, and then compares it every frame. I agree, for consistency's sake, that the same thing should happen in BitmapText. I'll add that to PR #1315.

**Comment by marcusstenbeck** [comment] 2015-01-04 15:03
Ok, I was wrong, it's actually possible to set the `tint` exactly in the way you want to do it. I've corrected and I'll add that to my PR.

**Comment by marcusstenbeck** [comment] 2015-01-07 00:43
@gre My fixes have been added to the `dev-rewrite` branch. So good news is that it's being fixed—bad news is that it may take a while before it surfaces in a release. Until then I suggest you pick a workaround and use it until then. Thanks for contributing!

**Comment by gre** [comment] 2015-01-07 06:12
Sure.
No problem.
Thanks
Le 7 janv. 2015 01:43, "Marcus Stenbeck" <notifications@github.com> a écrit
:

**Comment by englercj** [comment] 2015-01-07 06:32
I'm going to close this for now since it is in the dev-rewrite branch. When we merge to dev and have a working build you can let me know if this stops working.

**Closed by englercj** 2015-01-07 06:32 UTC
