### ISSUE TITLE
[V3-RC2] BitmapFont doesn't work

### ISSUE THREAD

**Issue by JiDW** [GoodBoyDigital/pixi.js#1568] opened 2015-03-20 11:37 UTC
1- .fnt files aren't considered as XML by RessourceLoader so it loads as plain text.
2- When the loader calls the BitmapFont parser, it gives a string instead of a DOM and the following parser fails to parse it to XML because it only test if "ressource.data" is empty or not, not if it is an actual XML.
3- Once it is parsed, it fails to retrieve the associated image file because it try to load it from the root, not using the path of the .fnt
4- After correcting the 3 things above, I discovered that .json went trough BitmapFont parse. May be caused by my own code.
5- I couldn't load every assets. It may be caused by the "concurrency" limit when you add files to the queue while it's already loading ? I don't know if it makes any sense, but what I know is that my loader didnt complete until I put "1000" to the concurrency limit. Go figure.
6- Even then, my BitmapText are all black. The baseTexture is ok and it is the correct font, but black, like if I had applied a "tint" to it.

Did you manage to make a bitmap font works with v3 ? If yes, can you provide me a .fnt to check if my XML is badly formed please ?

**Comment by englercj** [comment] 2015-03-20 14:48
1. you can force loading of any type with `xhrType`, for example:
```js
.add('key', 'url', { xhrType: Resource.XHR_RESPONSE_TYPE.DOCUMENT })
```

2. The bitmap font parser shouldn't even be doing what it is now for xml parsing. That stuff should be moved into an xml middleware that tries to massage text into xml. I'll be doing that this weekend along with other resource-loader work.

3. If the XML is loaded correctly it should load from the path in the xml, but relative to the xml location. LIkely this should be "relative to the xml location if the url in the xml is relative" but right now it is always relative to the xml, this was fixed in RC3.

4. All resources go through all middlewares, it is up to the middleware to decide if it should operate on the data or not, which is what [this code][check] does, this had some modification in RC3.

5. That sounds like a bug, can you create a repro case and post it to the englercj/resource-loader issue tracker?

6. The blackness is caused by the default tint on BitmapText being black, this was fixed in RC3.

[check]: https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/loaders/bitmapFontParser.js#L27-L31

**Comment by JiDW** [comment] 2015-03-20 15:45
Thanks englercj, I didn't know the RessourceLoader project was yours, thanks for your hard work !

1. Thanks, it will do the trick.
2. Ok, thanks.
3. Indeed, it works now
4. Indeed, RC3 made it work.
5. Done.
6. Thanks !

**Comment by englercj** [comment] 2015-03-21 02:32
Closing this since the only bugs left are in resource-loader, not pixi (except the xml which will move to resource loader soon).

**Closed by englercj** 2015-03-21 02:32 UTC
