### ISSUE TITLE
Issue with VideoTexture on IE11 and Firefox

### ISSUE THREAD

**Issue by StefanRehder** [GoodBoyDigital/pixi.js#1612] opened 2015-03-28 07:40 UTC
#### Issues with VideoTexture on IE11 and Firefox
I have some issues with PIXI.VideoTexture (This may be related to issue #1485).
It is working great in the Chrome browser for Windows, and in Safari on Mac/iPad/iPhone, And in the default browser of a newer ASUS tablet (Running Android).

But I experience issues in Internet Explorer on Windows and in Firefox on both Windows and Linux.
I really hope that you can help me figure this out. 
Maybe I am just using it wrong or maybe it is a bug?

##### Details of the issues I experience
In Internet Explorer on Windows I get a black box where the video should be (I hear the sound of the video) and I see these messages in the console (In danish unfortunately but i will translate below):
```
WEBGL11098: drawElements: Strukturen er en struktur, der ikke er opløftet til anden potens, eller ikke mipmap-fuldført
Fil: pixi.dev.js, Linje: 9377, Kolonne: 5
WEBGL11072: INVALID_VALUE: texImage2D: Denne strukturkilde understøttes ikke
Fil: pixi.dev.js, Linje: 8065, Kolonne: 5
```

Here I am trying to translate it into english:
```
WEBGL11098: drawElements: The structure is a structure, which is not raised to the power of 2, or not mipmap-completed.
Fil: pixi.dev.js, Line: 9377, Column: 5
WEBGL11072: INVALID_VALUE: texImage2D: This structure source is not supported
Fil: pixi.dev.js, Line: 8065, Column: 5
```

The first message is refering to these lines in PIXI.WebGLSpriteBatch.prototype.renderBatch:
```javascript
// now draw those suckas!
gl.drawElements(gl.TRIANGLES, size * 6, gl.UNSIGNED_SHORT, startIndex * 6 * 2);
```
The second message is refering to these lines in PIXI.WebGLRenderer.prototype.updateTexture :
```javascript
gl.bindTexture(gl.TEXTURE_2D, texture._glTextures[gl.id]);
gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL, texture.premultipliedAlpha);
```

##### It is not the format of my video
I tried to add the same video on a simple HTML5 page and it plays fine using the video tag, 
So it is not the format of my video that causes the issue. 

##### The Deus Demo video has the same issues
I experience the same issues with the video shown in the [Deus demo](http://www.goodboydigital.com/pixijs/examples/deus/) which is referenced in the PIXI.VideoTexture source code. When running the demo in Internet Explorer 11 I hear the sound of the movie (but it is not shown) and I get the same lines as described above in the console.

##### Code of my testpage
Here is the code of my testpage if needed:
```javascript
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
   <title>Test Page</title>
   <script src="../Scripts/Libraries/pixi.dev.js"></script>
</head>
<body>
   <script>

      // create an new instance of a pixi stage
      var stage = new PIXI.Stage(0xAFAFAF);

      // create a renderer instance
      var renderer = new PIXI.WebGLRenderer(800, 600);

      // add the renderer view element to the DOM
      document.body.appendChild(renderer.view);

      requestAnimFrame(render);

      // Test videoTexture
      var texture = PIXI.VideoTexture.fromUrl("../Resources/Movie/A1_x264.mp4");
      var testvideo = new PIXI.Sprite(texture);
      testvideo.scale.x = testvideo.scale.y = 0.25;
      testvideo.position.x = 50;
      testvideo.position.y = 50;
      stage.addChild(testvideo);

      function render() {

         requestAnimFrame(render);

         // render the stage
         renderer.render(stage);
      }

   </script>
</body>
</html>
```

**Comment by StefanRehder** [comment] 2015-03-28 12:00
Hi again,

I just tried it using the development build of Pixi (Pixi v3 I guess).
Unfortunately the issue is the same here.

Including the source code of my test page for v3 for reference.

```javascript
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
   <title>Test Page</title>
   <!--<script src="../Scripts/Libraries/pixi.dev.js"></script>-->
   <script src="../Scripts/Libraries/pixi.beta.js"></script>
</head>
<body>
   <script>
      // create an new instance of a pixi stage
      var stage = new PIXI.Stage(0xAFAFAF);

      // create a renderer instance
      var renderer = new PIXI.WebGLRenderer(800, 600);

      // add the renderer view element to the DOM
      document.body.appendChild(renderer.view);

      requestAnimationFrame(update);

      // Test videoTexture
      //var texture = PIXI.VideoTexture.fromUrl("../Resources/Movie/A1_x264.mp4");     // Old way to do it in Pixi V2
      var texture = PIXI.Texture.fromVideoUrl("../Resources/Movie/A1_x264.mp4");     // New in Pixi V3
      var testvideo = new PIXI.Sprite(texture);
      testvideo.scale.x = testvideo.scale.y = 0.25;
      testvideo.position.x = 50;
      testvideo.position.y = 50;
      stage.addChild(testvideo);

      function update() {
         requestAnimationFrame(update);

         // render the stage
         renderer.render(stage);
      }
   </script>
</body>
</html>
```

**Comment by englercj** [comment] 2015-03-28 16:38
Thanks for the details, we will be sure to look into this asap. I assume this works fine with the canvas renderer, just WebGL is giving you trouble?

**Comment by StefanRehder** [comment] 2015-03-29 12:41
Thanks for a fast reply.
When I use WebGLRenderer I have the issue as described above.

I just tried using autoDetectRenderer and autoDetectRecommendedRenderer and wrote the renderer to console afterwards. 

WebGLRenderer, autoDetectRenderer and autoDetectRecommendedRenderer all return an [object Object] in Internet Explorer 11 on Windows.
When i do the same in Chrome I see a WebGLRenderer in the console.

Maybe it is just the way IE11 handles objects or maybe there is an issue with the detecter?

When I try to force a CanvasRenderer i get this message (on both IE11, Firefox and Chrome):
TypeError: this.mapBlendModes is not a function  - Firefox
Uncaught TypeError: undefined is not a function  - Chrome
The object does not support the property or function 'mapBlendModes'  - IE11

Message occurs at this line 10951 in pixi.dev.js:
this.mapBlendModes();

Here is the code of my testpage trying to force CanvasRenderer (maybe I am doing it wrong):
```javascript
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
   <title>Test Page</title>
   <script src="../Scripts/Libraries/pixi.dev.js"></script> <!-- Pixi v2 -->
   <!--<script src="../Scripts/Libraries/pixi.beta.js"></script>--> <!-- Pixi v3 -->
</head>
<body>
   <script>
      // create an new instance of a pixi stage
      var stage = new PIXI.Stage(0xAFAFAF);

      // create a renderer instance
      //var renderer = new PIXI.WebGLRenderer(800, 600);
      var renderer = PIXI.CanvasRenderer(800, 600);
      //var renderer = PIXI.autoDetectRenderer(800, 600);
      //var renderer = PIXI.autoDetectRecommendedRenderer(800, 600);
      console.log("renderer is a", renderer);

      // add the renderer view element to the DOM
      document.body.appendChild(renderer.view);

      requestAnimationFrame(update);

      // Test videoTexture
      var texture = PIXI.VideoTexture.fromUrl("../Resources/Movie/A1_x264.mp4");     // Old way to do it in Pixi V2
      //var texture = PIXI.Texture.fromVideoUrl("../Resources/Movie/A1_x264.mp4");     // New way to do it in Pixi V3
      var testvideo = new PIXI.Sprite(texture);
      testvideo.scale.x = testvideo.scale.y = 0.25;
      testvideo.position.x = 50;
      testvideo.position.y = 50;
      stage.addChild(testvideo);

      function update() {
         requestAnimationFrame(update);

         // render the stage
         renderer.render(stage);
      }
   </script>
</body>
</html>
```

**Comment by StefanRehder** [comment] 2015-03-29 12:46
Thanks for a fast reply. Yes you assume correctly.
CanvasRenderer is working fine, I only have the issues when using WebGLRenderer.

**Comment by Fuglefjellet** [comment] 2015-04-09 13:27
I'm seeing the same problem as Stefan in IE11. Instead of rendering a video, a black rectangle is shown. This is only with the WebGL-renderer. Canvas works properly.

Firefox shows the same error as Stefan mentioned, and no video is rendered. This is in both WebGL and Canvas mode.

On the plus-side, VideoTexture works right on Chrome Android/iOS and Safari iOS. Unfortunately, videos on mobile devices refuse to auto-play, so some user interaction (a single click is enough) is required before a VideoTexture can be played there.

**Comment by paulgambrell** [comment] 2015-04-09 15:53
Having exactly the same issue on ff and ie, using the slightly different method of creating my own video element and passing it to textureFromVideo (which I'm doing solely to add the 'loop' attribute):

```javascript
this.video = document.createElement('video');
this.video.src = "res/Deposit/Video/fullmap.mp4";
this.video.autoPlay = true;
this.video.loop = true;
this.mapBackground = new PIXI.Sprite(PIXI.VideoTexture.textureFromVideo( this.video, PIXI.scaleModes.DEFAULT));
```

**Comment by ppluchon** [comment] 2015-04-14 11:34
Hello guys ! 
Will it be fixed on V2 too? 
If it's only for PIXI V3, do you think it is bug-proof enough to use it on production?
I'm currently using VideoTexture a lot on a big project with PIXI and it's a very bad news to me :/

Thanks !

**Comment by vanillabass** [comment] 2015-04-16 21:34
+1 Video texture not working with WebGLRenderer - only working with canvas.

**Comment by greglindquist** [comment] 2015-05-08 21:41
FWIW - The issue on this doesn't seem to be with PIXI, but with IE 11. There's an open bug that indicates the way you send video the webgl language is actually broken with the results found above. I seem to remember this was working at some point as well, so MS must have goofed something up and never bothered to fix it.

https://connect.microsoft.com/IE/feedback/details/927217/webgl-video-texture-support-is-broken-possible-regression

**Comment by englercj** [comment] 2015-05-08 22:04
Damn, looks like there isn't much we can do about this one :(

Alternatively, you could draw the video to a canvas manually, and use that as the texture for your sprite (see `Texture.fromCanvas()`). I'd rather not put that hack into the core lib though :/

**Comment by Fuglefjellet** [comment] 2015-05-09 10:50
I just upgraded my test-project to pixi.js v3, with the new VideoBaseTexture, and i thought I'd chime in with how it's working on WebGL:

Video textures now work in Firefox, on WebGL
. 
They still don't work in IE, but with a different error-message than i got on pixi.js v2. New error:
    WEBGL11072: INVALID_VALUE: texImage2D: This texture source is not supported
    File: pixi.js, Line: 12939, Column: 5

We might decide to just render our videos to canvases, and using them as textures like englercj suggests. Performance hopefully won't be terrible.

My test-setup is Windows 7 64Bit, with IE 11.

**Comment by greglindquist** [comment] 2015-05-12 18:01
We decided to force ie11 to the canvas renderer as well because of this. 

I've also notice that Chrome has a bad stuttering issue when playing videos, however; we're able to recreate the issue with just  a video tag and don't think the issue is with Pixi JS. disabling hardware video decoding in the flags set up page seemed to clear it up.

**Comment by englercj** [comment] 2015-05-13 04:06
Going to close this issue since it is a browser bug and the workaround is to use the CanvasRenderer or render to a canvas texture.

Thanks all, feel free to continue to update with extra information.

**Closed by englercj** 2015-05-13 04:06 UTC
Labels: Browser Bug, WebGL
