### ISSUE TITLE
[v3] Uncaught TypeError: CanvasGraphics.renderGraphics is not a function

### ISSUE THREAD

**Issue by miguelmoraleda** [GoodBoyDigital/pixi.js#1790] opened 2015-05-13 15:19 UTC
I just migrated to v3 and I'm getting this error. 

The renderGraphics function is being called in Graphics.js 823.

The renderGraphics function doesn't exist on CanvasGraphics.

**Comment by miguelmoraleda** [comment] 2015-05-13 15:33
The issue is only present when using CanvasRenderer. Is it deprecated?

**Comment by englercj** [comment] 2015-05-13 15:39
It most certainly does:

https://github.com/GoodBoyDigital/pixi.js/blob/master/src/core/renderers/canvas/utils/CanvasGraphics.js#L16

Do you have a running example of this?

**Comment by miguelmoraleda** [comment] 2015-05-13 15:52
You are totally right, it does.

Not sure why I'm getting this error when trying to use CanvasRenderer, no issues when ussing WebGLRenderer. 

I'm gonna publish an example of this ASAP and let you know.

**Comment by englercj** [comment] 2015-05-13 16:10
That method is only called with canvas renderer, it is how graphics are drawn to the canvas. You won't see that call in WebGL rendering because it doesn't use the CanvasGraphics object at all for that.

Looking forward to you test case.

**Comment by wojciak** [comment] 2015-05-13 20:17
You guys! Look!

**Comment by englercj** [comment] 2015-05-14 01:52
This was a regression, got it fixed in latest dev. Will hotfix shortly.

**Closed by englercj** 2015-05-14 01:52 UTC
Labels: bug

**Comment by miguelmoraleda** [comment] 2015-05-14 01:57
@englercj Thanks! Sorry, I couldn't build the test case.
