### ISSUE TITLE
Why is this path closed with 3.0.7 version

### ISSUE THREAD

**Issue by christophevx** [GoodBoyDigital/pixi.js#1932] opened 2015-07-01 08:25 UTC
The moveTo lineTo functions is not rendering like older versions of PIXI.

It seems that the new version of PIXI close path without reason (the same path was not closed with 3.0.6- version).

see this jsfiddle : https://jsfiddle.net/grefw7rz/

**Comment by GBagley** [comment] 2015-07-02 02:26
Same as this issue (workaround listed here): https://github.com/GoodBoyDigital/pixi.js/issues/1892

**Comment by englercj** [comment] 2015-07-07 16:24
Duplicate of #1892.

**Closed by englercj** 2015-07-07 16:24 UTC
