### ISSUE TITLE
video sprites scaled horizontally while renderer width > 4000

### ISSUE THREAD

**Issue by aegor** [GoodBoyDigital/pixi.js#1405] opened 2015-02-02 22:11 UTC
```javascript
var renderer = PIXI.autoDetectRenderer(3840, players.screeny, {resolution: 1});
```
width = 3840 - video not scaled horizontally; 4100 - video scaled horizontally about factor 1.05; 6000 - video scaled horizontally aboun factor 1.6;
https://github.com/aegor/pixitest/blob/master/index.html

**Comment by englercj** [comment] 2015-02-02 22:53
Not sure this has anything to do with pixi. Do you get a similar issue when drawing a video directly to a canvas of this size? Does this only happen with a specific renderer?

**Comment by GoodBoyDigital** [comment] 2015-02-15 21:50
closing for now as we need more info to figure out whats going on here. Thanks!

**Closed by GoodBoyDigital** 2015-02-15 21:50 UTC
Labels: need-more-info

**Comment by skevy** [comment] 2015-04-21 20:06
I can confirm this happens to me too. Trying to render a canvas in Chrome at 5760x1080.

**Comment by englercj** [comment] 2015-04-21 21:40
@skevy I pose the the same question I did originally:

> Curious if this is pixi or the browser. Do you get a similar issue when drawing a video directly to a canvas of this size? Does this only happen with a specific renderer?

Browsers have a max size a canvas can be before they just scale it, if you can show pixi has this behavior, but a raw canvas draw does not, then it is a bug and we can investigate. Otherwise, I'm assuming this is a browser/canvas issue and there is nothing we can do (simply) about it.

**Comment by skevy** [comment] 2015-04-21 21:44
You're right. I've been doing more research this afternoon. Looks like the max buffer size is 16384...if you divide by 4 for the RGBA4 render buffer...you get 4096. And that's the point where it starts breaking, not actually 4100.

https://github.com/mrdoob/three.js/issues/5194
