### ISSUE TITLE
[v3] cacheAsBitmap on iPad 2 (maybe others) messed up the sprite positions.

### ISSUE THREAD

**Issue by Danetag** [GoodBoyDigital/pixi.js#1736] opened 2015-04-28 20:05 UTC
Hey folks, 

I figured out that putting cacheAsBitmap = true on a sprite is affecting his positions on tablets (testing on Ipad 2, working OK on iPad mini...), even tho when I trace the object the positions are correct. 

Removing the cacheAsBitmap make it works normally. I think I might acts like that because of the screen resolution...

FYI:
- on iPad 2, window.devicePixelRatio returns 2, and it's messed up
- on ipad Mini. window.devicePixelRatio returns 1, and it's OK

**Comment by JiDW** [comment] 2015-04-29 10:01
Hi ! Do you have a test case ? Because I do not see this behavior in my game.

**Comment by englercj** [comment] 2015-05-15 15:42
I feel like this is a duplicate of something I saw recently: #1803

**Closed by englercj** 2015-05-15 15:42 UTC
Labels: need-more-info
