### ISSUE TITLE
DisplayObjectContainer click method not working

### ISSUE THREAD

**Issue by Arduinology** [GoodBoyDigital/pixi.js#1337] opened 2015-01-08 20:26 UTC
The mouse (click) events don't seem to fire on DisplayObjectContainer for me. Am I missing something? I even included a hitArea just in case.
```
    var DOC = new PIXI.DisplayObjectContainer();
    DOC.width = 10;
    DOC.height = 10;
    DOC.interactive = true;
    DOC.buttonMode = true;
    DOC.hitArea = new PIXI.Rectangle(0, 0, 10, 10);
    DOC.click = function(e) {
      console.log('Clicked');
    };
    stage.addChild(DOC);
    requestAnimationFrame(animate);
```

**Comment by englercj** [comment] 2015-01-10 03:41
Is the stage marked as interactive as well?

**Comment by the-architect** [comment] 2015-01-12 01:45
ran into this issue as well, but there is a trick to make it work:

if you fill the DisplayObjectContainer with an invisible Rectangle Graphic object, your click handler will work:

```javascript
this.backgroundLayer = new PIXI.DisplayObjectContainer();
this.background = new PIXI.Graphics();
this.background.beginFill(0x000000, 0.0);
this.background.drawRect(0, 0, this.stageSize.x, this.stageSize.y);
this.background.interactive = true;

....

this.background.click = function (e) {
  // do something with the event
}.bind(this);
```

**Comment by NikkiKoole** [comment] 2015-01-12 16:01
I don't have any problem running your code @Arduinology here's a fiddle showing it: http://jsfiddle.net/nikkikoole/ngma7snq/18/

**Comment by englercj** [comment] 2015-01-16 15:21
Closing thus since interactions are being rewritten and I can't reproduce this anyway.

**Closed by englercj** 2015-01-16 15:21 UTC
Labels: need-more-info
