### ISSUE TITLE
After many calls to drawCircle, webGL circles break

### ISSUE THREAD

**Issue by yousifucv** [GoodBoyDigital/pixi.js#1469] opened 2015-02-27 03:23 UTC
After many drawCircle calls (after 15 seconds or so), if you don't clear the context, then you get line bridges between circles, and no new circles are drawn. 

http://jsfiddle.net/3bz62h4p/2/

**Comment by englercj** [comment] 2015-02-27 03:53
Duplicate of #1076

**Closed by englercj** 2015-02-27 03:53 UTC
Labels: bug, duplicate, Graphics, WebGL
