### ISSUE TITLE
Errors when building pixi.js with Closure Compiler

### ISSUE THREAD

**Issue by sbondor** [GoodBoyDigital/pixi.js#1260] opened 2014-12-09 11:16 UTC
If I build pixi.dev.js with closure compiler using --warning_level VERBOSE, I get the following errors:

source/vendor/pixi.js/bin/pixi.dev.js:13901: ERROR - variable slot is undeclared
            if (slots[i].name == slotName) return slot[i];
                                                  ^

source/vendor/pixi.js/bin/pixi.dev.js:14052: ERROR - variable time is undeclared
        time += delta;
        ^

source/vendor/pixi.js/bin/pixi.dev.js:15879: ERROR - variable event is undeclared
    if( event.type === 'canplaythrough' )
        ^

source/vendor/pixi.js/bin/pixi.dev.js:18172: ERROR - variable exports is undeclared
    if (typeof exports !== 'undefined') {
               ^

source/vendor/pixi.js/bin/pixi.dev.js:18173: ERROR - variable module is undeclared
        if (typeof module !== 'undefined' && module.exports) {
                   ^

source/vendor/pixi.js/bin/pixi.dev.js:18177: ERROR - variable define is undeclared
    } else if (typeof define !== 'undefined' && define.amd) {
                      ^

Plus a ton of warnings which I'm not going to list here...

**Comment by englercj** [comment] 2015-02-10 16:40
Fixed in v3, just confirmed the new build works fine with closure compiler. There are a few warnings with the browserify bundle, mostly because it doesn't like things like `!function(){}` which is a common form making a function be evaluated as an expression.

**Closed by englercj** 2015-02-10 16:40 UTC
Labels: enhancement
