### ISSUE TITLE
matrix perspective transformation

### ISSUE THREAD

**Issue by pinguini** [GoodBoyDigital/pixi.js#1365] opened 2015-01-21 05:26 UTC
Hi i need an perspective transformation of sprite 

![perspective](https://cloud.githubusercontent.com/assets/5128663/5831674/e6fb13c0-a158-11e4-9902-278c1563619d.png)

but we have matrix as 
a | b | tx
c | d | ty
0 | 0 | 1
with this matrix we cannot do this 8(

**Comment by englercj** [comment] 2015-01-21 15:09
duplicate of #612

**Comment by pinguini** [comment] 2015-01-21 15:56
no skew is not a perspective transformation.
there is some count of transformations
all they are matrix
for example rotation, scale - affine transformation
if we want rotate on 45 than scale X by 2 we need multiply Matrixes
Mrotate*Mscale = Mfinaltransform
so we have some parameters of sprite in input: rotate, scale, skew, projectionpoint
at the end we can cache final transform as WorldTransform.

but for a fully usage we need use full matrix 3*3 not only "a b c d tx ty"

**Comment by englercj** [comment] 2015-01-21 16:28
Ah I misunderstood what you were asking for, sorry been screaming through issues lately.

I'm not sure this is something we want to put into pixi right now, but I'll leave it open as a reminder.

**Comment by GoodBoyDigital** [comment] 2015-01-21 16:30
very handy! 3D transforms will be a plugin for v3

**Comment by englercj** [comment] 2015-01-21 16:31
Most issues on this list could be plugins in v3, I'm just hoping the community steps up and builds some of them. We just don't have time to write them all ourselves.

**Comment by pinguini** [comment] 2015-01-21 16:38
i can try realize caching and multiplying matrices and pool it. but a have trouble with extending PIXI.matrix to full 3*3 and have no enough skill in WebGL to fix it in PIXI.

**Comment by GoodBoyDigital** [comment] 2015-01-25 16:30
@pinguini pixi only uses affine transforms at the moment as it is designed for 2D rendering only. A little 3D plugin will allow 4*4 matrix transforms later down the line though. cheers!

**Comment by pinguini** [comment] 2015-01-26 07:41
for perspective transformation we do not need in 4*4 matrix
http://habrahabr.ru/post/126269/   - sorry a can't find in english 8(
translate
![translate](https://cloud.githubusercontent.com/assets/5128663/5896470/e4c73842-a557-11e4-9bc5-692618e5e3a9.gif)
rotate
![rotate](https://cloud.githubusercontent.com/assets/5128663/5896468/e4c2b844-a557-11e4-813d-8b11fdd96271.gif)
scaling
![scale](https://cloud.githubusercontent.com/assets/5128663/5896471/e4c73ca2-a557-11e4-9e93-e68a07c035ab.gif)
affine transformation
![affine](https://cloud.githubusercontent.com/assets/5128663/5896469/e4c49d6c-a557-11e4-8444-5840fc5e043f.gif)
projection transformation
![projection](https://cloud.githubusercontent.com/assets/5128663/5896467/e4c22a6e-a557-11e4-9c94-9edbee740fa7.gif)

ABDE - scale rotate skew
CF - translation
ab - projection 
c - overall scale

**Comment by marklundin** [comment] 2015-03-05 13:56
Not entirely sure how pixi.js works but projection matrices are generally defined as 4x4 as they transform to homogenous coordinate space, `vec3( x, y, z, w )`

**Comment by GoodBoyDigital** [comment] 2015-03-05 14:47
true indeed! what you need is our new plugin pixiFLIP! http://www.goodboydigital.com/pixijs/pixiFLIP/
should be ready soon after the v3 release.

**Closed** 2015-03-08 19:08 UTC
Labels: feature-request

**Comment by alamboley** [comment] 2015-08-05 09:24
@englercj @GoodBoyDigital hey, does the plugin is no live somewhere? Can't find it!

**Comment by stbaer** [comment] 2015-08-05 11:35
@alamboley - theres only the [dev-flip](https://github.com/pixijs/pixi.js/tree/dev-flip) branch afaik.

Am also hoping this will be released as a plugin soon ( @GoodBoyDigital - can you give us any update on this? ).

**Comment by mrgoonie** [comment] 2017-02-28 07:20
Just asking, any chances that https://gameofbombs.github.io/pixi-bin can be merge into future release of PixiJS? Be able to use Sprite3d, Container3d, Camera is definitely useful tho.

**Comment by ivanpopelyshev** [comment] 2017-02-28 10:03
No, but I'll make new iteration in match :)
