### ISSUE TITLE
v2.0.0 displacementFilter multiple canvases

### ISSUE THREAD

**Issue by glafarge** [GoodBoyDigital/pixi.js#1122] opened 2014-11-05 15:05 UTC
Unexpected result with DisplacementFilter when I have more than one canvas in page.

[![v1.6.1](https://cloud.githubusercontent.com/assets/670645/4919688/5a4a3660-64fc-11e4-8d29-2142884c5fad.jpg)](http://jsfiddle.net/glafarge/6h84bpnk/)

[![v2 0 0](https://cloud.githubusercontent.com/assets/670645/4919693/604b9446-64fc-11e4-8c31-c61bef59bf90.jpg)](http://jsfiddle.net/glafarge/6h84bpnk/1)

Two fiddles to compare : 
v1.6.1 : http://jsfiddle.net/glafarge/6h84bpnk/
v2.0.0 : http://jsfiddle.net/glafarge/6h84bpnk/1

**Comment by englercj** [comment] 2015-01-08 16:44
This issue may be caused by #1238, hopefully this will be fixed in v3

**Comment by GoodBoyDigital** [comment] 2015-02-17 22:17
Boom! works like a champ in v3!

**Closed by GoodBoyDigital** 2015-02-17 22:17 UTC
Labels: bug

**Comment by glafarge** [comment] 2015-02-18 07:54
Thank you !! :)
