### ISSUE TITLE
AssetLoader and ImageLoader on password protected pages on Chrome

### ISSUE THREAD

**Issue by taseenb** [GoodBoyDigital/pixi.js#1149] opened 2014-11-10 16:05 UTC
Apparently it is impossible to load atlases on Chrome (a JSON file that points to an image file), when working on password protected pages with basic authentication. Chrome console shows a 401 (Authorization Required) error on the image and does not allow to download it to the browser:

```
GET http://webpage/confetti/confetti-spritesheet.png 401 (Authorization Required) 
```

The funny thing is that you can load the image directly without any problem:

```
var texture = PIXI.Texture.fromImage("http://webpage/confetti/confetti-spritesheet.png"); // this works!
```

Here is a probable reason: http://stackoverflow.com/questions/19244006/chrome-basic-auth-image-requests-return-401-but-not-when-called-directly

But this is not completely clear why we can't load an image with AssetLoader, but we can with Texture.fromImage(). Someone has an idea on how to fix this or a workaround?

**Comment by englercj** [comment] 2015-01-08 16:42
Pretty sure this is a duplicate of #1269 or #1234

**Closed by englercj** 2015-01-08 16:42 UTC
