### ISSUE TITLE
Proposal: 3 properties to manage object positioning

### ISSUE THREAD

**Issue by englercj** [GoodBoyDigital/pixi.js#997] opened 2014-09-24 22:59 UTC
### Proposal

I propose, there should be 2 properties on a DisplayObject: `origin` and `pivot`; and one extra property on a Sprite: `anchor`. These properties are defined below:

#### Origin

The `origin` would be a normalized point that describes where the position of the object is oriented. `(0, 0)` means the position of the object describes the top-left of the object, `(1, 1)` means the position describes the bottom-right of the object.

#### Pivot

The `pivot` would be a normalized point that describes the point at which the object rotates around. Again, `(0, 0)` is top-left, `(1, 1)` is bottom-right.

#### Anchor

For sprites, there is an extra property `anchor`. This is in addition to the previous properties that it inherits from DisplayObject. The `anchor` is a normalized point that describes where the top-left of the texture attaches to the object. `(0, 0)` is top-left of the texture is on the top-left of the object, `(1, 1)` is top-left of the texture is on the bottom-right of the object.

#### Conclusion

With these three properties you have the ability to do anything you need to with regard to positioning and rotating. It also reduces ambiguity that comes from having pivot be a pixel position, and anchor be normalized. Many issues arise from having the current implementation of `pivot` be a hybrid of the proposed `origin` and `pivot` and even more so from `anchor` being used to fill that gap. This solution clarifies the use of each property, removes ambiguity, and adds additional functionality.

**Comment by Arduinology** [comment] 2015-01-06 23:53
+1, pivot is awkward to use and I have yet to get it working, an anchor is a must in my opinion.

**Comment by Arduinology** [comment] 2015-01-07 18:13
As a follow up to this @englercj you suggested (0,0) to be top left and (1,1) to be bottom right for the origin, what if I have a map and I want to zoom in on whatever the cursor is pointed to. This would not work with such low granularity. What about a pixel based origin?

e.g. 500 x 500 rectangle, if I point to an object at 250x and 375y the origin would be (250,375). From there a scale transformation would respect that origin and zoom as intended.

**Comment by agamemnus** [comment] 2015-01-07 18:36
In Javascript, numbers are 64-bit floating-point IEEE numbers. The precision limits are the same regardless of the scale.

Anyway, in terms of map zoom, you should really be handling this by setting a scale and offset value on a stage.

**Comment by Arduinology** [comment] 2015-01-07 19:06
@agamemnus `stage.scale = 5;` has no effect on the stage scale.

**Comment by agamemnus** [comment] 2015-01-07 19:08
My bad. I was calling it a stage in my code but it's actually a DisplayObjectContainer ().

**Comment by Arduinology** [comment] 2015-01-07 19:11
@agamemnus see that is what I have done but there is no offset. I am having to set the pivot and then the scale of the DisplayObjectContainer, this gets complicated though. As you zoom in 0,0 of the mouse is no longer 0,0 of the DOC, it is now 125, 125 depending on how much you zoomed in. I am having issues accounting for this numerical transformation.

**Comment by agamemnus** [comment] 2015-01-07 19:22
I see. Maybe my code snippet can help you. ``offset_x`` and ``offset_y`` are the .x and .y values of the container.

````
 function jigsaw_onscroll (evt) {
  evt.preventDefault ()
  if (draw_area.controls_locked) return
  var xy = getXY (evt, action_area)
  var x = xy[0]
  var y = xy[1]
  var n = 1 + Math.abs(wheelDistance (evt)) / 4.5
  var zoom_factor = (getWheelData(evt) > 0) ? n : 1 / n
  jigsaw_doscroll (zoom_factor, x, y)
  
  // Returns +1 for a single wheel roll "up" and -1 for a single roll "down".
  function wheelDistance (evt) {
   var w = evt.wheelDelta, d = evt.detail
   if (!d) return w / 120                    // IE / Safari / Chrome.
   if (w) return w / d / 40 * d > 0 ? 1 : -1 // Opera.
   return -d / 3                             // Firefox.
  }
 }
 
 function jigsaw_doscroll (zoom_factor, x, y) {
  var old_scale = game_instance.zoom.scale
  x /= content_div.content_scale
  y /= content_div.content_scale
  var scale = old_scale * zoom_factor
  if (zoom_factor > 1) {
   if (scale > game_instance.zoom.scalemax) scale = game_instance.zoom.scalemax
  } else {
   if (scale < game_instance.zoom.scalemin) scale = game_instance.zoom.scalemin
  }
  
  var offset_x = (game_instance.zoom.offset_x - x) * (scale / game_instance.zoom.scale) + x
  var offset_y = (game_instance.zoom.offset_y - y) * (scale / game_instance.zoom.scale) + y
  
  game_instance.zoom.scale = scale
  game_instance.zoom.offset_x = offset_x
  game_instance.zoom.offset_y = offset_y
 }
````

**Comment by Arduinology** [comment] 2015-01-07 19:49
What does the `getXY()` function look like?

**Comment by agamemnus** [comment] 2015-01-07 20:07
````
function getXY (evt, target) {
 if (typeof target == "undefined") target = evt.target
 var rect = target.getBoundingClientRect(); return [evt.clientX - rect.left, evt.clientY - rect.top]
}
````

content_div is a centered HTML div that has CSS scaling applied to it. The canvas is attached to content_div.

You can see it in action here (Chrome only atm): http://tinyurl.com/llpn4hn

**Comment by Arduinology** [comment] 2015-01-07 20:37
Eh, I can see it working for you but am still unsure about many things like `getBoundingClientRect();` and `action_area`, maybe I am over complicating this.

**Comment by agamemnus** [comment] 2015-01-07 20:44
container.scale = scale
container.x = offset_x
container.y = offset_y

rect.left and rect.top are typically 0, I think. The important part is:
````
  var offset_x = (game_instance.zoom.offset_x - x) * (scale / game_instance.zoom.scale) + x
  var offset_y = (game_instance.zoom.offset_y - y) * (scale / game_instance.zoom.scale) + y
  game_instance.zoom.scale = scale
  game_instance.zoom.offset_x = offset_x
  game_instance.zoom.offset_y = offset_y
````

**Comment by Arduinology** [comment] 2015-01-07 20:54
@agamemnus I ended up getting it, code isn't the prettiest right now but it works. I will post my solution once I have things looking decent.

**Comment by Arduinology** [comment] 2015-01-07 22:25
@agamemnus and everyone here, you can see my implementation as a stand alone repo over here: https://github.com/Arduinology/Pixi-Pan-and-Zoom

**Comment by agamemnus** [comment] 2015-01-07 22:29
Great. Don't forget to add a license text or file (MIT is typical) so people can potentially use it.

**Comment by Arduinology** [comment] 2015-01-07 22:40
Thanks, added.

**Comment by GoodBoyDigital** [comment] 2015-02-02 23:55
Closing this one peeps. This seems like it could make a nice plugin for v3 though if anyone fancies the task! Cheers! :+1:

**Closed by GoodBoyDigital** 2015-02-02 23:55 UTC
Labels: enhancement
