### ISSUE TITLE
DIfference in Text rendering between Webkit and Firefox

### ISSUE THREAD

**Issue by ayamflow** [GoodBoyDigital/pixi.js#1520] opened 2015-03-12 12:33 UTC
Hi there! Another issue I stumbled upon.

This is a text rendered on webkit (safari & chrome looks the same): 
![webkit image](http://s24.postimg.org/jac6lpayd/Screen_Shot_2015_03_12_at_1_27_31_PM.png)

This one is Firefox:
![firefox image](http://s24.postimg.org/67gk2fkqd/Screen_Shot_2015_03_12_at_1_27_52_PM.png)

Using WebGL renderer. If I force Canvas renderer, the text is nice (but has a weird position). I don't understand why Firefox messes this up because `PIXI.Text` is supposed to be rendered on an off screen canvas (Context2D) either way right ?

I guess using `PIXI.BitmapText` would be an option at this point.
Thanks !

Update: Tested with BitmapText, and also with a different font, without success :'( Seems like a texture rendering issue ?
OSX Webkit:
![webkit bitmap](http://s1.postimg.org/mx1hicnjz/Screen_Shot_2015_03_12_at_4_20_38_PM.png)
OSX Firefox:
![firefox bitmap](http://s1.postimg.org/y8456puf3/Screen_Shot_2015_03_12_at_4_20_32_PM.png)

**Comment by alvinsight** [comment] 2015-03-12 12:49
Is this on Firefox mobile ? Firefox for android generally blurs any text for me :/

**Comment by ayamflow** [comment] 2015-03-12 13:01
Ah yeah sorry I forgot to precise: it's on Firefox Mac OS X. Though the same issue arise on mobile Webkit (Android & iOS) :(
I need to check if the font can be guilty here.

**Comment by GoodBoyDigital** [comment] 2015-03-12 15:31
eeeewwwww! that looks nasty :/
almost looks like it rendered twice??

**Comment by ayamflow** [comment] 2015-03-12 15:39
So I updated the main post, I tested with BitmapText, using 2 fonts, and also using a .png with the same text as a Sprite, the result is the same. I tested on Pixi v2 and the problem doesn't appear!

Even worse: I tested with a JPG with white background, and the same in PNG (so no transparency). Same result !

**Comment by GoodBoyDigital** [comment] 2015-03-12 15:43
very strange indeed! If you could provide a fiddle / example I will take a look.. 

cheers man! :+1:

**Comment by ayamflow** [comment] 2015-03-12 16:58
Gah, I found it... Removing `renderer.antialias` solve that thing...
Also if I keep antialias but remove my background (a 1920x1080 `PIXI.Sprite`), it also solve that thing...
Here is a test case : http://ayamflow.fr/pixi/text-render/

**Comment by gordyr** [comment] 2015-03-16 23:45
This is caused by the FXAA shader.  And is a classic issue with FXAA in general (the only issue really, in every other way FXAA is excellent).

Almost certainly you will find that your hardware/software configuration is unable to support native multisample anti aliasing and PIXI is therefore switching to FXAA.  Which for 99% of apps/games is a great choice (better than using native MSAA also, particularly performance-wise)

However, the algorithm, as clever as it is, just cannot deal with text properly when placed against a non transparent background.

Just a suggestion for the fantastic PIXI dev team.  There are several other nice shader based anti-aliasing algorithms out there.  None are as performant or as nice looking in general as FXAA but perhaps it would be worth adding another option for those that are going to be dealing with text frequently?

**Comment by englercj** [comment] 2015-03-18 02:08
@gordyr Nice catch, will definitely look into the best way to solve this.

**Comment by ayamflow** [comment] 2015-03-20 12:40
Is there a way I can apply the FXAA only on my images, not the text? I tried quickly to use it a a regular filter but it was messed up (the image looked like a Renaissance painting). Not sure how to use the uniforms I guess.

**Comment by GoodBoyDigital** [comment] 2015-03-20 12:49
until I apply a fix - might be worth trying to add a background image or graphics object to the stage that covers the full scene.

**Comment by mattdesl** [comment] 2015-03-22 17:57
IMHO the FXAA magic should be removed and the decision offloaded to the user, see my thoughts [here](https://github.com/GoodBoyDigital/pixi.js/issues/1555#issuecomment-84666007)

**Comment by GoodBoyDigital** [comment] 2015-04-12 22:46
closing this guy for now as its more of an FXAA issue than a font one. Cheers! :+1:

**Closed by GoodBoyDigital** 2015-04-12 22:46 UTC
Labels: bug, Text, WebGL
