### ISSUE TITLE
[v3] New Loader doesn't pass arguments

### ISSUE THREAD

**Issue by JiDW** [GoodBoyDigital/pixi.js#1542] opened 2015-03-17 10:21 UTC
Hello,

At this moment, the loader is able to use two arguments : baseUrl and options (crossOrigin, etc).

But at https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/loaders/loader.js#L25 there is no arguments referenced, and they are not applied when calling "ResourceLoader.call(this);"

Another bug is at https://github.com/GoodBoyDigital/pixi.js/blob/dev/bin/pixi.js#L2966 (not sure what file it is, sorry) where only the first argument is used for each call.

It means that baseUrl doesn't work and you can't load cross origin files

Regards.

**Comment by adireddy** [comment] 2015-03-17 11:29
baseUrl is now the property of the class.

`_loader.baseUrl = "url";`

And you can set options while adding each asset to the loader.

`_loader.add(id, url, options);`

Haxe pixi sample can be found here. https://github.com/adireddy/haxe-pixi/blob/master/samples/loader/Main.hx

**Comment by JiDW** [comment] 2015-03-17 11:51
But how to add an array with options ? I can understand why baseUrl is not an argument anymore but why options aren't transfered when you add an array ? For me, it's a bug.

**Comment by adireddy** [comment] 2015-03-17 13:07
If you look at the `add` method here https://github.com/englercj/resource-loader/blob/master/src/Loader.js I don't think you cab add array to load multiple assets in one go.

**Comment by JiDW** [comment] 2015-03-17 13:13
I do think you can, that would be a useless drawback from v2, and I believe this is exactly what these lines are for : 

```javascript
if (Array.isArray(name)) {
        for (var i = 0; i < name.length; ++i) {
            this.add(name[i]);
        }

        return this;
    }
```

**Comment by adireddy** [comment] 2015-03-17 13:22
Yes you are right. I just looked at the docs.

* @param [name] {string} The name of the resource to load, if not passed the url is used.
* @param url {string} The url for this resource, relative to the baseUrl of this loader.

Could be a bug then as you said.

**Comment by englercj** [comment] 2015-03-18 02:02
> But at https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/loaders/loader.js#L25 there is no arguments referenced, and they are not applied when calling "ResourceLoader.call(this);"

That is true, we can make it pass along the params passed to the ctor. For now, if you want to setup the base url you can just do `loader.baseUrl = '';`.

> Another bug is at https://github.com/GoodBoyDigital/pixi.js/blob/dev/bin/pixi.js#L2966 (not sure what file it is, sorry) where only the first argument is used for each call.

Not a bug, this syntax is there so that you can pass many different types of params to the `.add()` method. For example, all of these work:

```js
loader
    // normal param syntax
    .add('key', 'http://...', function () {})
    .add('http://...', function () {})
    .add('http://...')

    // object syntax
    .add({
        name: 'key2',
        url: 'http://...'
    }, function () {})
    .add({
        url: 'http://...'
    }, function () {})
    .add({
        name: 'key3',
        url: 'http://...'
        onComplete: function () {}
    })
    .add({
        url: 'https://...',
        onComplete: function () {},
        crossOrigin: true
    })

    // you can also pass an array of objects or urls or both
    .add([
        { name: 'key4', url: 'http://...', onComplete: function () {} },
        { url: 'http://...', onComplete: function () {} },
        'http://...'
    ]);
```

The loader module used in pixi is [resource-loader](https://github.com/englercj/resource-loader). I should probably update the docs found on the add method to inform the user about the different available syntaxes.

Hopefully that answers your question.

**Comment by JiDW** [comment] 2015-03-18 12:01
Thanks for the explanations :)

**Comment by GoodBoyDigital** [comment] 2015-03-21 17:54
can we close this one? seem we are good here?

**Closed** 2015-03-21 17:59 UTC
Labels: Loaders, question
