### ISSUE TITLE
Suggestion PR - Why not z and perspective 3D

### ISSUE THREAD

**Issue by Inateno** [GoodBoyDigital/pixi.js#1674] opened 2015-04-17 15:35 UTC
Hey guys.

I just finished the migration of my engine on PIXI and I was wondering why there is not perspective feature inside PIXI (by adding a z attribute on DisplayObject position).

Imo this is a cool feature and it's pretty hard to setup out of the rendering stuff (as I did lol), and when you want to create parallax stuff you just have to change the z of your object.

Without Camera I don't know how I could do it but I can try to add this inside PIXI, as I did for mine, and then PR, if you think it's great (this will certainly take me lot of time).

Cya

**Comment by Cristy94** [comment] 2015-04-17 15:51
I think that at the current version you can change the Z order by re-ordering elements in the stage children array. Some auxiliary methods for doing this would be great.

**Comment by Inateno** [comment] 2015-04-17 16:02
I'm not talking about a "z-index" system (like CSS z-index, simple sorting) I talk about perspective with 2D objects (it's like a perspective 3D but you are not projecting 3D object, but "planes").

**Comment by englercj** [comment] 2015-04-17 18:24
Duplicate of #1365, there will be a plugin for this when v3 is released.

**Closed** 2015-04-17 18:24 UTC

**Comment by Inateno** [comment] 2015-04-17 18:27
MMmh okay, I wasn't asking for "perspective transformation" but if there is the depth perspective that's okay for me. (also perspective transformation look awesome)
