### ISSUE TITLE
DisplayObject with click and mouseup events being destroyed.

### ISSUE THREAD

**Issue by aholla** [GoodBoyDigital/pixi.js#1904] opened 2015-06-18 12:00 UTC
HI, I have a displayobject with a mouseup and a click event.

If on the click event I remove the displayobject from the displaylist and null it I get an error. This occues in the INteraction manager when it tries to test the displayojectes "visible" property. However the displayobject is null.

I am guess this is because the "mouseup" event is still being processed after the click event even though the display object has been removed.

**Comment by englercj** [comment] 2015-06-18 13:13
Duplicate of #1817, and #1821

**Closed by englercj** 2015-06-18 13:13 UTC
