### ISSUE TITLE
Destroying and recreating canvas breaks WebGL rendering

### ISSUE THREAD

**Issue by 4ian** [GoodBoyDigital/pixi.js#1329] opened 2015-01-07 17:30 UTC
Since I've upgraded Pixi from 1.6.1 to the latest 2.2.3, I experience glitches when creating and destroying a Pixi view with WebGL.

Here is an example:
http://compilgames.net/code/pixi-canvas-destruction/index.html

I'm using Pixi 2.2.3. Click on *Create* to launch the creation of a renderer, with its view being added in the document body. Click on *Destroy* to remove the renderer (it is removed from the DOM *and* the ``renderer`` variable is set to ``null`` to ensure that it is freed from memory). After doing several cycle of creation/destruction (4 or 5 cycles on my computer, using Chromium 39 on Ubuntu 14.04), everything rendered by Pixi is now black (``PIXI.Graphics``, ``PIXI.Sprite``... Only the stage background color is still ok). 

When using Pixi 1.6.1, the rendering and everything is still working flawlessly after several creation/destruction of the canvas. You can try it here: 
http://compilgames.net/code/pixi-canvas-destruction/index161.html

Also in both case, when reaching ~10/15 cycles of creation/destruction, I get a warning in the console: ``WARNING: Too many active WebGL contexts. Oldest context will be lost.``. This warning doesn't seem to be harmful because here we don't care to lose the oldest context as long as the current one is alive.
When using the canvas renderer, the problem doesn't seem to arise.

**Comment by englercj** [comment] 2015-01-07 17:40
I'm pretty sure this is a duplicate of #1238

**Comment by 4ian** [comment] 2015-01-07 18:06
Thanks, I didn't see the duplicate while searching! So I'll stick with 1.6.1 until the rewrite is done :)

**Closed** 2015-01-07 22:34 UTC
